### ISSUE TITLE
Support `strategy.fail-fast: false`

### ISSUE THREAD

**Issue by dominykas** [pkgjs/action#26]
Also `strategy.max-parallel` while at it.

**Comment by ljharb** [comment]
That should be the default - fail-fast: true is super annoying.

**Comment by dominykas** [comment]
I do agree, and I did consider that, but I'm not sure I'm brave enough to go for that without more feedback.

Do you think changing this value should be considered a breaking change down the road?

**Comment by ljharb** [comment]
I’ve switched all 300+ of my repos to not fail fast; i think most use cases for open source projects would want that.

Changing defaults is definitely a breaking change (and a default of “true” is always bizarre, but that one’s on GitHub)
