### ISSUE TITLE
Step can fail but action can still return as passing

### ISSUE THREAD

**Issue by Trott** [pkgjs/action#55]
Ref: https://github.com/nodejs/github-bot/actions/runs/4354160252

**Comment by Trott** [comment]
I guess this might be intentional?

https://github.com/pkgjs/action/blob/main/.github/workflows/node-test.yaml#L184

**Comment by ljharb** [comment]
Yes, because `npm ls` will fail if the dep graph is invalid, and many projects' dep graphs are sadly invalid.

Note that the installation itself failing should still fail the job; only the `npm ls` step has continue-on-error.
